In [29]:
import numpy as np 
import time

In [6]:
#brodcasting 
arr1= np.array([1,2,3,4,5])
arr2= np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr1.shape,arr2.shape)
print(arr1+arr2)


(5,) (2, 5)
[[ 2  4  6  8 10]
 [ 6  8 10 12 14]]


In [8]:
#normalize
arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
std_dev= np.std(arr)

normalized_arr =(arr-mean)/std_dev
print(normalized_arr)
print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [12]:
arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))

15
120
0
4
3.0
1.4142135623730951


In [19]:
arr = np.array([1,2,3,4,5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))
print(np.log(arr))
print(np.exp(arr))
print(np.log2(arr))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         1.         1.5849625  2.         2.32192809]


In [34]:
#rounding 
print(np.round(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

arr =np.array([1,-2,8,-3,4,5,2,5])

print(np.unique(arr))
print(np.round(3.14))
print(np.sort(arr))
print(np.abs(arr))


3.0
3.0
3.0
[-3 -2  1  2  4  5  8]
3.0
[-3 -2  1  2  4  5  5  8]
[1 2 8 3 4 5 2 5]
